(* generated by dune *)

(** @canonical Debug_protocol.Debug_protocol_types *)
module Debug_protocol_types = Debug_protocol__Debug_protocol_types

(** @canonical Debug_protocol.Util *)
module Util = Debug_protocol__Util
